# Change these first
owner: devOS-Sanity-Edition # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: "devOS Maven [mvn.devos.one]"
    url: https://mvn.devos.one/releases/cat.txt
    method: GET
  - name: devOS Site
    url: https://devos.one
    assignees:
      - asojidev
  - name: Git
    url: https://git.devos.one
  - name: TeamCity
    url: https://tc.devos.gay
    expectedStatusCodes:
      - 401 # it's not authenticated so ofc it thinks this
  # - name: LibreTranslate Backend
  #   url: https://libretranslate.devos.gay/languages
  #   method: GET
  - name: Unity Hotspot
    url: https://unitymultiplayer.online/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.devos.one
  # baseUrl: /upptime
  logoUrl: https://avatars.githubusercontent.com/u/77142119?v=4
  name: "devOS: Sanity Edition Public Status"
  introTitle: "Welcome to the devOS Status Page!"
  introMessage: Here you'll see the status on our various sites, and if anything has happened recently.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  themeUrl: https://status.devos.one/theme.css

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

assignees:
  - CephalonCosmic
  # - bluebeargreen-2
